# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20180105_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 21, 57, 3, 257583, tzinfo=utc)),
        ),
    ]
