# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20180105_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment',
            new_name='approved_comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 22, 0, 1, 291946, tzinfo=utc)),
        ),
    ]
